---
- name: Install PostgreSQL and configure database
  hosts: localhost
  become: yes  # Run tasks with sudo (root) privileges

  vars:
    postgres_db_name: "your_database_name"
    postgres_user: "your_username"
    postgres_password: "your_password"

  tasks:
    - name: Install PostgreSQL and its dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-contrib

    - name: "Install Python packages"
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary

    - name: Start and enable PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL user
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        encrypted: yes
        state: present

    - name: Grant all privileges on the database to the user
      postgresql_privs:
        database: "{{ postgres_db_name }}"
        user: "{{ postgres_user }}"
        priv: ALL
        state: present
