---
- name: Basic Web Server Deployment
  hosts: web_servers
  become: true  # Run tasks with sudo

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present  # Ensure Nginx is installed

    - name: Deploy HTML Page
      copy:
        content: "<html><body><h1>Hello, Ansible!</h1></body></html>"
        dest: "/var/www/html/index.html"
