---
- name: Install Nginx
  hosts: localhost
  become: yes  # Run tasks with sudo (root) privileges

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"  # Conditional task execution based on the OS family

    - name: Install Nginx
      apt:
        name: nginx
        state: present  # Ensure that the package is installed

    - name: Start Nginx service
      service:
        name: nginx
        state: started  # Ensure that the service is running

    - name: Enable Nginx service on boot
      service:
        name: nginx
        enabled: yes  # Ensure that the service starts on boot

