---
- name: Install PostgreSQL and configure database
  hosts: localhost
  become: yes  # Run tasks with sudo (root) privileges

  vars:
    postgres_db_name: "your_database_name"
    postgres_user: "your_username"
    postgres_password: "your_password"

  tasks:
    - name: Install PostgreSQL and its dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql

    - name: "Install Python packages"
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Start postgresql service"
      shell: "/etc/init.d/postgresql start"

    - name: Create database
      remote_user: root
      become: yes
      become_method: su
      become_user: postgres
      postgresql_db:
        name: my_db
