version: '3'
services:
  ansible-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-container
    ports:
      - 80:80
      - 5432:5432
    command: tail -f /dev/null  # Keep the container running
    volumes:
      - ./ansible-playbooks:/ansible-playbooks  # Mount a local directory with your Ansible playbooks
